### ISSUE TITLE
Configuration window is freezing.

### ISSUE THREAD

**Issue by cjdduarte** [RuzuStudios/ruzu-pop-ups#9] opened 2022-12-25 14:33 UTC
Configuration window is freezing.
Anki 2.1.55 qt6

![image](https://user-images.githubusercontent.com/42243532/209472017-8c31c0d8-d9c5-400d-b071-993cad0110e0.png)

**Comment by CharlesHenry** [comment] 2022-12-26 23:02
I'm unable to reproduce this with the same version of Anki and qt6 on Windows. Have you tried running it without other plugins enabled? If it's an incompatibility issue with another plugin and we identify the other plugin I should be able to reproduce/find the issue and hopefully a fix it.

**Comment by CharlesHenry** [comment] 2022-12-27 01:10
I was able to reproduce the issue from the add-ons list page. I've put in a fix for this in v0.0.4 now

**Closed by CharlesHenry** 2022-12-27 01:10 UTC
